undo temp changes

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -76,40 +76,40 @@ jobs:
         with:
           node-version: "14"
 
-      # - name: Npm tool install
-      #   run: npm install -g npm@8
+      - name: Npm tool install
+        run: npm install -g npm@8
 
-      # - name: Npm ci
-      #   run: npm ci
+      - name: Npm ci
+        run: npm ci
 
-      # - name: Npm test on cloud
-      #   id: test-cloud
-      #   env:
-      #     ACCESS_KEY: ${{ secrets.DEV_CA_PUBLIC_USE_INTEGRATION_TEST_ACCESS_KEY }}
-      #     SERVICE_PRINCIPAL_KEY: ${{ secrets.DEV_CA_PUBLIC_USE_TESTOAUTHSERVICEPRINCIPAL_SERVICE_PRINCIPAL_KEY }}
-      #   run: npm run test:Cloud
+      - name: Npm test on cloud
+        id: test-cloud
+        env:
+          ACCESS_KEY: ${{ secrets.DEV_CA_PUBLIC_USE_INTEGRATION_TEST_ACCESS_KEY }}
+          SERVICE_PRINCIPAL_KEY: ${{ secrets.DEV_CA_PUBLIC_USE_TESTOAUTHSERVICEPRINCIPAL_SERVICE_PRINCIPAL_KEY }}
+        run: npm run test:Cloud
 
-      # - name: Npm test on self-hosted
-      #   if: always() && (steps.test-cloud.outcome == 'success' || steps.test-cloud.outcome == 'failure')
-      #   env:
-      #     REPOSITORY_ID: ${{ secrets.APISERVER_REPOSITORY_ID }}
-      #     APISERVER_USERNAME:  ${{ secrets.APISERVER_USERNAME }}
-      #     APISERVER_PASSWORD:  ${{ secrets.APISERVER_PASSWORD }}
-      #     APISERVER_REPOSITORY_API_BASE_URL:  ${{ secrets.APISERVER_REPOSITORY_API_BASE_URL }}
-      #     ACCESS_KEY: ${{ secrets.DEV_CA_PUBLIC_USE_INTEGRATION_TEST_ACCESS_KEY }}
-      #     SERVICE_PRINCIPAL_KEY: ${{ secrets.DEV_CA_PUBLIC_USE_TESTOAUTHSERVICEPRINCIPAL_SERVICE_PRINCIPAL_KEY }}
-      #   run: npm run test:SelfHosted
+      - name: Npm test on self-hosted
+        if: always() && (steps.test-cloud.outcome == 'success' || steps.test-cloud.outcome == 'failure')
+        env:
+          REPOSITORY_ID: ${{ secrets.APISERVER_REPOSITORY_ID }}
+          APISERVER_USERNAME:  ${{ secrets.APISERVER_USERNAME }}
+          APISERVER_PASSWORD:  ${{ secrets.APISERVER_PASSWORD }}
+          APISERVER_REPOSITORY_API_BASE_URL:  ${{ secrets.APISERVER_REPOSITORY_API_BASE_URL }}
+          ACCESS_KEY: ${{ secrets.DEV_CA_PUBLIC_USE_INTEGRATION_TEST_ACCESS_KEY }}
+          SERVICE_PRINCIPAL_KEY: ${{ secrets.DEV_CA_PUBLIC_USE_TESTOAUTHSERVICEPRINCIPAL_SERVICE_PRINCIPAL_KEY }}
+        run: npm run test:SelfHosted
 
-      # - name: Test Report
-      #   uses: dorny/test-reporter@v1
-      #   if: success() || failure() # run this step even if previous step failed
-      #   with:
-      #     name: Jest Test Results
-      #     path: ./*.xml
-      #     reporter: jest-junit
-      #     only-summary: "false"
-      #     list-tests: "failed"
-      #     fail-on-error: "false"
+      - name: Test Report
+        uses: dorny/test-reporter@v1
+        if: success() || failure() # run this step even if previous step failed
+        with:
+          name: Jest Test Results
+          path: ./*.xml
+          reporter: jest-junit
+          only-summary: "false"
+          list-tests: "failed"
+          fail-on-error: "false"
 
 
   build-documentation:
@@ -175,19 +175,19 @@ jobs:
         run: echo "NpmPackageVersion=${{ env.NPM_VERSION }}--preview-${{ github.run_id }}" >> $GITHUB_ENV
 
       - name: npm version
-        run: echo ${{ env.NpmPackageVersion }} 
+        run: npm version ${{ env.NpmPackageVersion }} --no-git-tag-version
 
-      # - name: Npm publish
-      #   run: npm publish  --access public  --tag next
-      #   env:
-      #     NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
+      - name: Npm publish
+        run: npm publish  --access public  --tag next
+        env:
+          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
 
-      # - name: Tag commit
-      #   uses: rickstaa/action-create-tag@v1
-      #   with:
-      #     tag: ${{ env.NpmPackageVersion }}
-      #     commit_sha: ${{ github.sha }}
-      #     message: Workflow run ${{github.server_url}}/${{github.repository}}/actions/runs/${{ github.run_id}}
+      - name: Tag commit
+        uses: rickstaa/action-create-tag@v1
+        with:
+          tag: ${{ env.NpmPackageVersion }}
+          commit_sha: ${{ github.sha }}
+          message: Workflow run ${{github.server_url}}/${{github.repository}}/actions/runs/${{ github.run_id}}
 
 
   publish-production-package:
