removed log and reformatted

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -2,17 +2,15 @@ name: Test, build, and publish lf-oauth-api-client
 
 on:
   push:
-    branches: [ '\d+.x' ]
+    branches: ['\d+.x']
   pull_request:
-    branches: [ '\d+.x' ]
+    branches: ['\d+.x']
 
   # Allows you to run this workflow manually from the Actions tab
   workflow_dispatch:
 
 env:
   NPM_VERSION: "1.0.0"
-
-
 
 # A workflow run is made up of one or more jobs that can run sequentially or in parallel
 jobs:
@@ -21,11 +19,8 @@ jobs:
     environment: preview
     env:
       DEV_CA_PUBLIC_USE_INTEGRATION_TEST_ACCESS_KEY: ${{ secrets.DEV_CA_PUBLIC_USE_INTEGRATION_TEST_ACCESS_KEY }}
-      DEV_CA_PUBLIC_USE_TESTOAUTHSERVICEPRINCIPAL_SERVICE_PRINCIPAL_KEY:  ${{ secrets.DEV_CA_PUBLIC_USE_TESTOAUTHSERVICEPRINCIPAL_SERVICE_PRINCIPAL_KEY }}
+      DEV_CA_PUBLIC_USE_TESTOAUTHSERVICEPRINCIPAL_SERVICE_PRINCIPAL_KEY: ${{ secrets.DEV_CA_PUBLIC_USE_TESTOAUTHSERVICEPRINCIPAL_SERVICE_PRINCIPAL_KEY }}
     steps:
-      - name: Echo build number 2
-        run: echo ${{env.DEV_CA_PUBLIC_USE_TESTOAUTHSERVICEPRINCIPAL_SERVICE_PRINCIPAL_KEY}}
-
       - uses: actions/checkout@v2
 
       - name: Echo build number
@@ -34,7 +29,7 @@ jobs:
       - name: Setup Node.js environment
         uses: actions/setup-node@v2.5.1
         with:
-          node-version: '14'
+          node-version: "14"
 
       - name: Npm tool install
         run: npm install -g npm@8
@@ -47,15 +42,15 @@ jobs:
 
       - name: Test Report
         uses: dorny/test-reporter@v1
-        if: success() || failure()    # run this step even if previous step failed
+        if: success() || failure() # run this step even if previous step failed
         with:
           name: Jest Test Results
           path: ./*.xml
           reporter: jest-junit
-          only-summary: 'true'
-          fail-on-error: 'false'
+          only-summary: "true"
+          fail-on-error: "false"
   build:
-    needs: [ test ] # wait for tests to finish
+    needs: [test] # wait for tests to finish
     runs-on: ubuntu-latest
     env:
       NPM_TOKEN: dummy
@@ -73,7 +68,7 @@ jobs:
       - name: Setup Node.js environment
         uses: actions/setup-node@v2.5.1
         with:
-          node-version: '14'
+          node-version: "14"
 
       - name: Npm tool install
         run: npm install -g npm@8
@@ -124,7 +119,7 @@ jobs:
     runs-on: ubuntu-latest
     environment: preview
     if: ${{ github.run_attempt != 1 }}
-    needs: [ build ] # wait for build to finish
+    needs: [build] # wait for build to finish
     steps:
       - uses: actions/checkout@v2
         with:
@@ -138,14 +133,13 @@ jobs:
       - name: Setup Node.js environment
         uses: actions/setup-node@v2.5.1
         with:
-          node-version: '14'
+          node-version: "14"
 
       - name: Npm tool install
         run: npm install -g npm@8
 
       - name: set NpmPackageVersion as preview version from downloaded artifact
         run: echo "NpmPackageVersion=${{ env.NPM_VERSION }}--preview-${{ github.run_id }}" >> $GITHUB_ENV
-
 
       - name: npm version
         run: npm version ${{ env.NpmPackageVersion }} --no-git-tag-version
@@ -174,7 +168,7 @@ jobs:
     runs-on: ubuntu-latest
     environment: production
     if: ${{ github.run_attempt != 1 }}
-    needs: [ build ]
+    needs: [build]
     steps:
       - uses: actions/checkout@v2
         with:
@@ -188,7 +182,7 @@ jobs:
       - name: Setup Node.js environment
         uses: actions/setup-node@v2.5.1
         with:
-          node-version: '14'
+          node-version: "14"
 
       - name: Npm tool install
         run: npm install -g npm@8
